### ISSUE TITLE
Bold text on some properties

### ISSUE THREAD

**Issue by kolyasya** [zeh/vsc-theme-actual-obsidian#1]
Hello, thank you for great theme.
I've just installed it, and see some issues with bold text:

![image](https://cloud.githubusercontent.com/assets/3371143/22320801/7f95cfcc-e3a0-11e6-9608-c179046de922.png)

This is how it looks on my Atom editor with the same theme:

![image](https://cloud.githubusercontent.com/assets/3371143/22320814/a160ecae-e3a0-11e6-971a-4e6a88dfd01e.png)

**Comment by zeh** [comment]
Hey @Kolyasya,

Sorry, I didn't see this issue before - I must have turned off notifications by mistake. My bad.

I just did an update to the theme that removes a bunch of unnecessary bolds and add a few missing scopes. Please install 2.0.0 when you can! (You may need to have to re-select the theme again from the menu)

**Comment by zeh** [comment]
Closed as it should be fixed. Please let me know if you run into any other issue.

**Comment by kolyasya** [comment]
Hello! I've reinstalled theme and still have bold text

![image](https://cloud.githubusercontent.com/assets/3371143/22616473/b0212fe0-eabe-11e6-9389-0e4f142b1740.png)

The language is Javascript React if it matters

**Comment by zeh** [comment]
Hey @Kolyasya, I've updated it once again (2.1.x) with further bold removals. I'm still keeping some on constants, but trying to be careful about it to make sure it's changing only the things I want to change (the new inspector is helpful, but it stops working sometimes so it's been hard to properly find the right scope).
